### ISSUE TITLE
Feature request: Ability to cycle tabs from keyboard

### ISSUE THREAD

**Issue by mcclure** [PintaProject/Pinta#594]
**Description**
If I have opened many tabs, I would like to be able to navigate those tabs from the keyboard rather than using the mouse. A good shortcut that fits with other apps such as Firefox would be CTRL-TAB for the next tab and CTRL-SHIFT-TAB for the previous.

**Additional context**
At the moment (I am using 2.1.1 from the Ubuntu Snap Store), it is possible to click the tab header to select an orange outline around it, then press the left or right arrow keys to select the next or previous tab. However, upon doing this the tab header immediately deselects so you cannot do this more than once. Additionally, "tab" and "shift-tab" can be used to select on-screen elements, and this includes the tab header. But using either of these two existing keyboard shortcuts to switch tabs more than say twice in a row is entirely impractical.

**Comment by cameronwhite** [comment]
I think this might have worked before but was lost in the GTK3 port for Pinta 2.0, which had a complete overhaul of the tab system to use `GtkNotebook`. Using `Ctrl+PageUp` might work since I think that shortcut is hardcoded into `GtkNotebook`, but using `Alt+1/2/3/4/etc` to go to a specific tab is also an option.

The good news is this is already fixed in the master branch as part of the GTK4 port! This came as part of porting the tab bar to use https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.TabBar.html
