### ISSUE TITLE
Which dotnet version is required

### ISSUE THREAD

**Issue by NicoHood** [PintaProject/Pinta#616]
ArchLinux recently updated their dotnet runtime to 8. We still use v7 in the pkgbuild:
https://archlinux.org/packages/extra/any/pinta/

The issue is discussed here:
https://bbs.archlinux.org/viewtopic.php?id=290910

Now my question is: Is that even still correct? In the readme dotnet8 is stated? What should I set as correct version here? Would even newer version work?

**Comment by cameronwhite** [comment]
The `master` branch was recently updated to .NET 8 which is probably what you noticed in the README.

For Pinta 2.1, it'll be looking for .NET 6 or 7 when building. That said, it would be very easy to patch it to build against .NET 8 if that's easiest in your scenario. I think probably all you need is https://github.com/PintaProject/Pinta/pull/595/files#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810 which will override the target framework to `net8.0`, and we haven't needed any code changes or encountered other issues on the master branch with net8.0

These version checks should maybe be adjusted to allow unknown future .NET versions, since backwards compatibility of .NET releases has been extremely good so far
