### ISSUE TITLE
Better support for KDE Plasma

### ISSUE THREAD

**Issue by MajorTomDE** [PintaProject/Pinta#649]
Hello Pinta Team,

I know, Pinta is mainly for GTK. Neverthless there is also the KDE Plasma Desktop ;-)
In KDE Plasma it is possible to enable an GNOME/GTK style. But currently Pinta don't support it.

I have choosen an dark theme, but Pinta is light and also the fonts are to large.
In the top panel you can see the KDE Plasma "Global Menu Applet". If this is activated, the menu in the application window should normally be hidden. Unfortunately, this does not happen.

![pinta](https://github.com/PintaProject/Pinta/assets/76742790/492394f4-a88f-4d29-bee7-d4440a9654f2)

So my suggestion for an upcoming release is an better support for KDE Plasma.
I think this will make many people happy who are using KDE. Pinta is a great and simple tool für editing picuture and exactly what I need.

Happy new year and all the best
Tom

**Comment by cameronwhite** [comment]
I suspect at least some of the issues should be fixed on the master branch of Pinta which is ported to GTK4 / libadwaita (Pinta 2.1 is GTK3).
I haven't tested on KDE yet, but on other platforms at least Pinta now switches to a dark theme depending on the system settings

**Comment by MajorTomDE** [comment]
Woohoo, this sounds great. Thanks for the information.

**Comment by igor2x** [comment]
@MajorTomDE, I use Pinta 2.2-development from master branch as a user not as developer and I would also like to point: 
1. Pinta 2.2 is not using standard menus anymore (Gtk4 philosophy) like it used to in Pinta 2.1.1 (Gtk3 philosophy).
![image](https://github.com/PintaProject/Pinta/assets/10895030/e2f24654-defb-48d8-b2d8-12e9d186d575)


2. Pinta 2.2 now supports automatic color schema changes according to operating system setting. I tested it in Ubuntu 23.10 (it is Gnome) and Pinta automatically switches color schema if operating system color scheme is changed. Additionally Pinta 2.2 also supports manual changes of color scheme. For example you can have dark theme on operating system and white scheme on Pinta or vice versa.
![image](https://github.com/PintaProject/Pinta/assets/10895030/c8fd99ae-4a3b-4a5b-bb3f-10c8b26234e0)


**TRY IT OUT:**
I suggest to try Pinta 2.2-development from master. It is super easy to try out. You don't install anything, just unzip and run executable, so you can't break anything on your system.

Instructions:
a) Make sure you are logged into Github (if not sign in).
b) Go to link: https://github.com/PintaProject/Pinta/actions/workflows/build.yml?query=branch%3Amaster
c) Click on top member that appears (just to make sure check that you can see options in red rectangle first).
![image](https://github.com/PintaProject/Pinta/assets/10895030/b8ec6cd0-eec4-4adf-9588-081b39d743ef)
d) Scroll down to the bottom of web page where the Artifacts are and click on "Pinta-linux-dotnet-8.0.x.zip" and browser will download the file. NOTE: If link is not clicable, then you are most probably not signed into Github. Sign-into Github first.
![image](https://github.com/PintaProject/Pinta/assets/10895030/5418505b-6a94-48e2-8eac-e21d17dcfc00)
e) From here I like to work in terminal (by you may chose otherwise). I just do:
```
cd ~/Download/
# Note: Bellow command will extract files to current directory.
# You can copy zip file to some other directory if you prefer not to extract to $HOME/Downloads directory.
unzip Pinta-linux-dotnet-8.0.x.zip.zip
unzip pinta-2.2.zip
./Pinta
```
NOTE: If you want to delete Pinta 2.2-development, just delete all the files extracted by above steps.

Please do some test and report back how does Pinta 2.2-dev work on KDE Plasma.
If you spot some issue, please report each issue in its own bug report - one issue one bug report.
