### ISSUE TITLE
cant install pinta

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#690]
![image](https://github.com/PintaProject/Pinta/assets/132342905/a2e1e0ec-66b0-4716-bdf8-c974fe5ba3de)
just getting thes error message whenever i try to install

**Comment by cameronwhite** [comment]
I tried installing the same windows build of Pinta as the webpage in your image, and it installed successfully for me

However, the version number should (somewhat confusingly) be 2.2, not 2.1.1, since this build is on the `gtk3` branch of Pinta 2.2 and the fixes haven't yet been ported to the 2.1 release branch
So I'm guessing either you're installing the wrong .exe , or there's some issue with uninstalling the previous version you had installed on your system

**Comment by temginson** [comment]
do i basically need to reinstall my system?

**Comment by temginson** [comment]
![image](https://github.com/PintaProject/Pinta/assets/132342905/2f34caa8-f693-4541-9c96-152404c6994a)

**Comment by temginson** [comment]
okay i have gotten it working now there was a hidden pinta folder in C:\Program Files\

**Comment by cameronwhite** [comment]
OK thanks, sounds like there was something left over from a previous install
